title: Algoric
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://lsg154.github.com/lsg154.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Post
   url: /post

